# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b5e1765aee30558b92ab154f64520985454b98159b452f5a2361e2bac6014f193ea0cacbbd7f96e5eb9b0b32c228de2bd2307b7532933027f70e0c9ad3395b42

test:
  secret_key_base: ebf7c939d79510fb4be911ee417835fb48b240f40a141be20fe563166523ec69c9789b2907395a898c04e03523f82dfedb866b19cb576cb76d48511f98855541

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
